// Feedback actions
export const GET_REQUEST_TO_FEEDBACK = "GET_REQUEST_TO_FEEDBACK";
export const POST_REQUEST_TO_FEEDBACK = "POST_REQUEST_TO_FEEDBACK";

// User profile actions
export const GET_REQUEST_TO_USER_PROFILE = "GET_REQUEST_TO_USER_PROFILE";
export const PUT_REQUEST_TO_USER_PROFILE = "PUT_REQUEST_TO_USER_PROFILE";

export const GET_REQUEST_TO_VEHICLES = "GET_REQUEST_TO_VEHICLES";
export const GET_REQUEST_TO_LOCATION_DETAILS_VEHICLES = "GET_REQUEST_TO_LOCATION_DETAILS_VEHICLES";


export const GET_REQUEST_TO_BOOKING = "GET_REQUEST_TO_BOOKING";
export const POST_REQUEST_TO_BOOKING = "POST_REQUEST_TO_BOOKING";


export const GET_REQUEST_TO_BOOKING_LIST = "GET_REQUEST_TO_BOOKING_LIST";