export const GET_REQUEST_TO_FEEDBACK = "GET_REQUEST_TO_FEEDBACK"
export const POST_REQUEST_TO_FEEDBACK = "POST_REQUEST_TO_FEEDBACK"


export const GET_REQUEST_TO_USER_PROFILE = "GET_REQUEST_TO_USER_PROFILE"
export const PUT_REQUEST_TO_USER_PROFILE = "PUT_REQUEST_TO_USER_PROFILE"